name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: |
          github.event_name == 'push'
          && (github.ref == 'refs/heads/main' || github.head_ref == 'refs/heads/master')
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: ${{ secrets.AWS_CODEDEPLOY_REGION }}
# AWS CLI Docs: https://docs.aws.amazon.com/codedeploy/latest/userguide/deployments-create-cli.html
      - name: Deploy to CodeDeploy
        # success() checks if the previous job was canceled or not
        run: |
          aws deploy create-deployment \
          --deployment-group-name dev_group \
          --description="$GITHUB_SHA" \
          --application-name Git_Application \
          --github-location repository="$GITHUB_REPOSITORY",commitId="$GITHUB_SHA"
